### ISSUE TITLE
Ubuntu 18.04 LTS support

### ISSUE THREAD

**Issue by abdulbasetbasher** [mdminhazulhaque/beceem-cscm#1]
hello 
there is over 500K HUAWEI WiMax BM338 in libya and ther 1 isp here
nobody can install Linux and use internet
its same to Banglalion wimax.
i remember i follow one of you blog post in 2014 and i run HUAWEI WiMax BM338 in ubuntu 14.04
but when i try to run same on Ubuntu 18.04
nothing happen i cannot compile the beceem source on Ubuntu 18.04
so i need help.

sorry for my English. thank you

**Comment by mdminhazulhaque** [comment]
Hi @abdulbasetbasher,

It's a good news that you can run BM338 on Ubuntu 14.04. Sadly, Linux dropped the support for the driver of the USB dongle from kernel 3.18. So you can either compile the module by yourself, or keep using Ubuntu 14.04. Even you can use Ubuntu 14.04 on a cheap SBC (NanoPi or OrangePi) and use it as a router.
